import { KeyboardTheme } from '../types';

export interface ThemeConfig {
  id: KeyboardTheme;
  name: string;
  category: 'dark' | 'light';
  tagline: string;
  dotColor: string;
  badge?: string;
  preview: {
    bg: string;
    keyBg: string;
    keyText: string;
    accent: string;
    border: string;
  };
  // Outer phone frame / screen background
  phoneShellBg: string;
  phoneWallpaper: string;
  statusBarClass: string;
  homeBarClass: string;
  
  // Sandbox Chat
  chatHeaderBg: string;
  chatBodyBg: string;
  chatQuickBarBg: string;
  quickPromptChip: string;
  userBubble: string;
  partnerBubble: string;
  inputBarBg: string;
  inputFieldBg: string;
  
  // Smart Bar
  smartBarBg: string;
  smartBarBorder: string;
  pillBg: string;
  accentColor: string;
  
  // Keyboard Container & Keys
  keyboardChassisBg: string;
  keyNormal: string;
  keyAction: string;
  keyActionActive: string;
  keySpace: string;
  keyPopup: string;
}

export const THEME_CONFIGS: Record<KeyboardTheme, ThemeConfig> = {
  'cyber-slate': {
    id: 'cyber-slate',
    name: 'Obsidian Titanium',
    category: 'dark',
    tagline: 'Precision dark titanium with electric sapphire accents',
    dotColor: '#3b82f6',
    badge: 'PRO',
    preview: {
      bg: 'bg-[#0e1217]',
      keyBg: 'bg-[#1e2633]',
      keyText: 'text-neutral-100',
      accent: 'bg-blue-500',
      border: 'border-blue-500/40',
    },
    phoneShellBg: 'bg-[#090d12]',
    phoneWallpaper: 'bg-gradient-to-b from-[#0e141d] via-[#0b0f15] to-[#080b0f]',
    statusBarClass: 'bg-[#0e141d] text-neutral-300 border-b border-neutral-800/80',
    homeBarClass: 'bg-[#0e141d]',
    chatHeaderBg: 'bg-[#0f1622]/95 border-neutral-800/80 text-white backdrop-blur-md',
    chatBodyBg: 'bg-[#090d12] text-neutral-100',
    chatQuickBarBg: 'bg-[#0d131c]/90 border-neutral-800/70',
    quickPromptChip: 'bg-[#17202e] hover:bg-[#1f2b3e] text-neutral-200 border border-neutral-700/60 shadow-xs',
    userBubble: 'bg-gradient-to-br from-blue-600 to-indigo-600 text-white shadow-md shadow-blue-900/20 border border-blue-400/20',
    partnerBubble: 'bg-[#161f2c] text-neutral-100 border border-neutral-700/60 shadow-xs',
    inputBarBg: 'bg-[#0d131c] border-neutral-800',
    inputFieldBg: 'bg-[#151c27] border-neutral-700/80 text-white placeholder:text-neutral-500',
    smartBarBg: 'bg-[#0f1622] border-neutral-800/80 text-neutral-100',
    smartBarBorder: 'border-neutral-800/80',
    pillBg: 'bg-[#172130] border-neutral-700/80 text-neutral-200',
    accentColor: '#3b82f6',
    keyboardChassisBg: 'bg-[#0c1017] border-t border-neutral-800/90 shadow-[inset_0_1px_0_rgba(255,255,255,0.05)]',
    keyNormal: 'bg-[#1c2430] hover:bg-[#232d3d] active:bg-[#161c26] text-neutral-100 font-semibold border-t border-white/10 shadow-[0_2px_0_0_#0f141c] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-[#131923] hover:bg-[#192230] active:bg-[#0f141c] text-neutral-300 font-medium border-t border-white/5 shadow-[0_2px_0_0_#090d12] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-blue-600 text-white font-semibold border-t border-blue-400/30 shadow-[0_2px_0_0_#1d4ed8]',
    keySpace: 'bg-[#1c2430] hover:bg-[#232d3d] text-neutral-400 border-t border-white/10 shadow-[0_2px_0_0_#0f141c] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-[#1a222e] text-white border border-blue-500/40 shadow-2xl shadow-black/80',
  },

  'nordic-frost': {
    id: 'nordic-frost',
    name: 'Nordic Alpine',
    category: 'light',
    tagline: 'Crisp architectural minimalism with icy sky accents',
    dotColor: '#0284c7',
    badge: 'NEW',
    preview: {
      bg: 'bg-[#f1f5f9]',
      keyBg: 'bg-white',
      keyText: 'text-slate-900',
      accent: 'bg-sky-500',
      border: 'border-sky-300',
    },
    phoneShellBg: 'bg-[#f8fafc]',
    phoneWallpaper: 'bg-gradient-to-b from-[#f1f5f9] via-[#f8fafc] to-[#f1f5f9]',
    statusBarClass: 'bg-[#f1f5f9] text-slate-800 border-b border-slate-200',
    homeBarClass: 'bg-[#e2e8f0]',
    chatHeaderBg: 'bg-white/95 border-slate-200 text-slate-900 backdrop-blur-md',
    chatBodyBg: 'bg-[#f8fafc] text-slate-900',
    chatQuickBarBg: 'bg-[#f1f5f9] border-slate-200',
    quickPromptChip: 'bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 shadow-xs',
    userBubble: 'bg-gradient-to-br from-sky-600 to-blue-600 text-white shadow-md shadow-sky-600/15 border border-sky-400/30',
    partnerBubble: 'bg-white text-slate-900 border border-slate-200/90 shadow-xs',
    inputBarBg: 'bg-white border-slate-200',
    inputFieldBg: 'bg-slate-100 border-slate-200 text-slate-900 placeholder:text-slate-400',
    smartBarBg: 'bg-[#f1f5f9] border-slate-200 text-slate-900',
    smartBarBorder: 'border-slate-200',
    pillBg: 'bg-white border-slate-200 text-slate-800',
    accentColor: '#0284c7',
    keyboardChassisBg: 'bg-[#e2e8f0] border-t border-slate-300 shadow-[inset_0_1px_0_rgba(255,255,255,0.6)]',
    keyNormal: 'bg-white hover:bg-slate-50 active:bg-slate-100 text-slate-900 font-semibold border-b border-slate-200 shadow-[0_2px_0_0_#cbd5e1] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-[#d8e0ea] hover:bg-[#ccd5e0] active:bg-[#c0c9d4] text-slate-700 font-medium shadow-[0_2px_0_0_#b0bcc9] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-sky-600 text-white font-semibold shadow-[0_2px_0_0_#0369a1]',
    keySpace: 'bg-white hover:bg-slate-50 text-slate-500 shadow-[0_2px_0_0_#cbd5e1] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-white text-slate-900 border border-slate-300 shadow-xl',
  },

  'champagne-gold': {
    id: 'champagne-gold',
    name: 'Cashmere & Sand',
    category: 'light',
    tagline: 'Warm editorial cream palette inspired by luxury linen & ceramics',
    dotColor: '#d97706',
    badge: 'LUXURY',
    preview: {
      bg: 'bg-[#f4efe6]',
      keyBg: 'bg-[#fffdf9]',
      keyText: 'text-stone-900',
      accent: 'bg-amber-600',
      border: 'border-amber-300',
    },
    phoneShellBg: 'bg-[#fcfaf7]',
    phoneWallpaper: 'bg-gradient-to-b from-[#f7f2ea] via-[#fcfaf7] to-[#f4eee4]',
    statusBarClass: 'bg-[#f4eee4] text-stone-800 border-b border-stone-300/80',
    homeBarClass: 'bg-[#ede5d8]',
    chatHeaderBg: 'bg-[#faf7f2]/95 border-stone-300/80 text-stone-900 backdrop-blur-md',
    chatBodyBg: 'bg-[#fcfaf7] text-stone-900',
    chatQuickBarBg: 'bg-[#f5efe5] border-stone-300/70',
    quickPromptChip: 'bg-[#fffdf9] hover:bg-[#f6f1e8] text-stone-800 border border-stone-300 shadow-xs',
    userBubble: 'bg-gradient-to-br from-amber-700 to-amber-800 text-white shadow-md shadow-amber-900/15 border border-amber-500/30',
    partnerBubble: 'bg-[#fffdf9] text-stone-900 border border-stone-300 shadow-xs',
    inputBarBg: 'bg-[#f7f3eb] border-stone-300',
    inputFieldBg: 'bg-[#eae3d5]/70 border-stone-300 text-stone-900 placeholder:text-stone-500',
    smartBarBg: 'bg-[#f5efe5] border-stone-300 text-stone-900',
    smartBarBorder: 'border-stone-300',
    pillBg: 'bg-[#fffdf9] border-stone-300 text-stone-800',
    accentColor: '#d97706',
    keyboardChassisBg: 'bg-[#eae3d5] border-t border-stone-300 shadow-[inset_0_1px_0_rgba(255,255,255,0.7)]',
    keyNormal: 'bg-[#fffdf9] hover:bg-[#faf6ee] active:bg-[#f2ecde] text-stone-900 font-semibold border-b border-stone-200/80 shadow-[0_2px_0_0_#d5cca] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-[#ddd4c4] hover:bg-[#d0c6b4] active:bg-[#c4b9a6] text-stone-800 font-medium shadow-[0_2px_0_0_#b8ac98] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-amber-700 text-white font-semibold shadow-[0_2px_0_0_#92400e]',
    keySpace: 'bg-[#fffdf9] hover:bg-[#faf6ee] text-stone-500 shadow-[0_2px_0_0_#d5ccbe] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-[#fffdf9] text-stone-900 border border-stone-300 shadow-xl',
  },

  'emerald-sage': {
    id: 'emerald-sage',
    name: 'Botanical Jade',
    category: 'dark',
    tagline: 'Serene deep jade velvet with luminous mint accents',
    dotColor: '#10b981',
    badge: 'ZEN',
    preview: {
      bg: 'bg-[#091512]',
      keyBg: 'bg-[#142822]',
      keyText: 'text-emerald-100',
      accent: 'bg-emerald-500',
      border: 'border-emerald-500/40',
    },
    phoneShellBg: 'bg-[#060e0c]',
    phoneWallpaper: 'bg-gradient-to-b from-[#0a1814] via-[#060e0c] to-[#040908]',
    statusBarClass: 'bg-[#0a1814] text-emerald-300 border-b border-emerald-950',
    homeBarClass: 'bg-[#0a1814]',
    chatHeaderBg: 'bg-[#0b1b17]/95 border-emerald-900/60 text-white backdrop-blur-md',
    chatBodyBg: 'bg-[#060e0c] text-neutral-100',
    chatQuickBarBg: 'bg-[#081512] border-emerald-900/50',
    quickPromptChip: 'bg-[#11241f] hover:bg-[#19332c] text-emerald-200 border border-emerald-800/60 shadow-xs',
    userBubble: 'bg-gradient-to-br from-emerald-600 to-teal-700 text-white shadow-md shadow-emerald-950/40 border border-emerald-400/30',
    partnerBubble: 'bg-[#10221d] text-emerald-100 border border-emerald-900/60 shadow-xs',
    inputBarBg: 'bg-[#081512] border-emerald-900/60',
    inputFieldBg: 'bg-[#0e211b] border-emerald-800/60 text-emerald-100 placeholder:text-emerald-600/80',
    smartBarBg: 'bg-[#0b1a16] border-emerald-900/60 text-emerald-100',
    smartBarBorder: 'border-emerald-900/60',
    pillBg: 'bg-[#122620] border-emerald-800/60 text-emerald-200',
    accentColor: '#10b981',
    keyboardChassisBg: 'bg-[#071310] border-t border-emerald-950 shadow-[inset_0_1px_0_rgba(255,255,255,0.03)]',
    keyNormal: 'bg-[#132721] hover:bg-[#1a342c] active:bg-[#0e1d18] text-emerald-50 font-semibold border-t border-white/5 shadow-[0_2px_0_0_#060e0c] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-[#0c1c17] hover:bg-[#112620] active:bg-[#081410] text-emerald-300 font-medium border-t border-white/5 shadow-[0_2px_0_0_#030706] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-emerald-600 text-white font-semibold shadow-[0_2px_0_0_#047857]',
    keySpace: 'bg-[#132721] hover:bg-[#1a342c] text-emerald-400 shadow-[0_2px_0_0_#060e0c] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-[#122822] text-white border border-emerald-500/50 shadow-2xl',
  },

  'ios-dark': {
    id: 'ios-dark',
    name: 'Apple iOS Dark',
    category: 'dark',
    tagline: 'Authentic frosted Cupertino keycaps with 3D tactile ridges',
    dotColor: '#007aff',
    preview: {
      bg: 'bg-[#1c1c1e]',
      keyBg: 'bg-[#545458]',
      keyText: 'text-white',
      accent: 'bg-blue-500',
      border: 'border-neutral-600',
    },
    phoneShellBg: 'bg-black',
    phoneWallpaper: 'bg-[#000000]',
    statusBarClass: 'bg-[#161618] text-white border-b border-[#2c2c2e]',
    homeBarClass: 'bg-[#161618]',
    chatHeaderBg: 'bg-[#1c1c1e]/95 border-[#2c2c2e] text-white backdrop-blur-md',
    chatBodyBg: 'bg-black text-white',
    chatQuickBarBg: 'bg-[#161618] border-[#2c2c2e]',
    quickPromptChip: 'bg-[#2c2c2e] hover:bg-[#3a3a3c] text-neutral-200 border border-[#3a3a3c] shadow-xs',
    userBubble: 'bg-[#007aff] text-white shadow-md shadow-blue-950/30',
    partnerBubble: 'bg-[#262628] text-white border border-[#38383a]',
    inputBarBg: 'bg-[#1c1c1e] border-[#2c2c2e]',
    inputFieldBg: 'bg-[#2c2c2e] border-[#3a3a3c] text-white placeholder:text-neutral-400',
    smartBarBg: 'bg-[#1c1c1e] border-[#2c2c2e] text-white',
    smartBarBorder: 'border-[#2c2c2e]',
    pillBg: 'bg-[#2c2c2e] border-[#3a3a3c] text-white',
    accentColor: '#007aff',
    keyboardChassisBg: 'bg-[#1c1c1e] border-t border-[#2c2c2e]',
    keyNormal: 'bg-[#545458] hover:bg-[#636366] active:bg-[#48484a] text-white font-normal text-lg shadow-[0_1.5px_0_0_#1c1c1e] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-[#3a3a3c] hover:bg-[#48484a] active:bg-[#2c2c2e] text-neutral-200 font-medium shadow-[0_1.5px_0_0_#1c1c1e] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-[#007aff] text-white font-semibold shadow-[0_1.5px_0_0_#0051a8]',
    keySpace: 'bg-[#545458] hover:bg-[#636366] text-neutral-300 shadow-[0_1.5px_0_0_#1c1c1e] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-[#545458] text-white border border-[#636366] shadow-2xl',
  },

  'ios-light': {
    id: 'ios-light',
    name: 'Apple iOS Light',
    category: 'light',
    tagline: 'Iconic iOS light keyboard with pure white keycaps & crisp drop shadows',
    dotColor: '#007aff',
    preview: {
      bg: 'bg-[#d1d5db]',
      keyBg: 'bg-white',
      keyText: 'text-black',
      accent: 'bg-[#007aff]',
      border: 'border-neutral-300',
    },
    phoneShellBg: 'bg-neutral-100',
    phoneWallpaper: 'bg-[#f2f2f7]',
    statusBarClass: 'bg-[#e5e5ea] text-black border-b border-[#d1d1d6]',
    homeBarClass: 'bg-[#d1d1d6]',
    chatHeaderBg: 'bg-[#ffffff]/95 border-[#e5e5ea] text-black backdrop-blur-md',
    chatBodyBg: 'bg-[#f2f2f7] text-black',
    chatQuickBarBg: 'bg-[#e5e5ea] border-[#d1d1d6]',
    quickPromptChip: 'bg-white hover:bg-neutral-50 text-neutral-800 border border-[#d1d1d6] shadow-xs',
    userBubble: 'bg-[#007aff] text-white shadow-md shadow-blue-500/20',
    partnerBubble: 'bg-white text-black border border-[#e5e5ea] shadow-xs',
    inputBarBg: 'bg-[#ffffff] border-[#e5e5ea]',
    inputFieldBg: 'bg-[#e5e5ea] border-[#d1d1d6] text-black placeholder:text-neutral-500',
    smartBarBg: 'bg-[#e5e5ea] border-[#d1d1d6] text-black',
    smartBarBorder: 'border-[#d1d1d6]',
    pillBg: 'bg-white border-[#d1d1d6] text-black',
    accentColor: '#007aff',
    keyboardChassisBg: 'bg-[#d1d5db] border-t border-[#b9bdc5]',
    keyNormal: 'bg-white hover:bg-neutral-50 active:bg-[#e5e5ea] text-black font-normal text-lg shadow-[0_1.5px_0_0_#8e8e93] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-[#b3b7be] hover:bg-[#a5abb3] active:bg-[#999fa8] text-black font-medium shadow-[0_1.5px_0_0_#7f848c] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-[#007aff] text-white font-semibold shadow-[0_1.5px_0_0_#0051a8]',
    keySpace: 'bg-white hover:bg-neutral-50 text-neutral-600 shadow-[0_1.5px_0_0_#8e8e93] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-white text-black border border-[#d1d1d6] shadow-2xl',
  },

  'midnight-blue': {
    id: 'midnight-blue',
    name: 'Midnight Nebula',
    category: 'dark',
    tagline: 'Deep cosmic indigo with luminous neon accents',
    dotColor: '#6366f1',
    badge: 'OLED',
    preview: {
      bg: 'bg-[#0b1021]',
      keyBg: 'bg-[#182245]',
      keyText: 'text-indigo-100',
      accent: 'bg-indigo-500',
      border: 'border-indigo-500/40',
    },
    phoneShellBg: 'bg-[#070a17]',
    phoneWallpaper: 'bg-gradient-to-b from-[#0e1630] via-[#070b18] to-[#050813]',
    statusBarClass: 'bg-[#0e1630] text-indigo-200 border-b border-indigo-950',
    homeBarClass: 'bg-[#0e1630]',
    chatHeaderBg: 'bg-[#0f1733]/95 border-indigo-900/60 text-white backdrop-blur-md',
    chatBodyBg: 'bg-[#070a17] text-white',
    chatQuickBarBg: 'bg-[#0a1126] border-indigo-900/50',
    quickPromptChip: 'bg-[#152044] hover:bg-[#1d2c5e] text-indigo-200 border border-indigo-800/60 shadow-xs',
    userBubble: 'bg-gradient-to-br from-indigo-600 to-purple-600 text-white shadow-md shadow-indigo-950/40 border border-indigo-400/30',
    partnerBubble: 'bg-[#131b38] text-indigo-100 border border-indigo-900/60 shadow-xs',
    inputBarBg: 'bg-[#0a1126] border-indigo-900/60',
    inputFieldBg: 'bg-[#121c3d] border-indigo-800/60 text-white placeholder:text-indigo-400/60',
    smartBarBg: 'bg-[#0d1530] border-indigo-900/60 text-white',
    smartBarBorder: 'border-indigo-900/60',
    pillBg: 'bg-[#162147] border-indigo-800/60 text-indigo-200',
    accentColor: '#6366f1',
    keyboardChassisBg: 'bg-[#090e1f] border-t border-indigo-950',
    keyNormal: 'bg-[#192447] hover:bg-[#21305c] active:bg-[#121b36] text-white font-semibold border-t border-indigo-400/10 shadow-[0_2px_0_0_#0a0e1e] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-[#111933] hover:bg-[#172347] active:bg-[#0b1021] text-indigo-300 font-medium border-t border-white/5 shadow-[0_2px_0_0_#050812] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-indigo-600 text-white font-semibold shadow-[0_2px_0_0_#4338ca]',
    keySpace: 'bg-[#192447] hover:bg-[#21305c] text-indigo-300 shadow-[0_2px_0_0_#0a0e1e] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-[#1c2850] text-white border border-indigo-500/50 shadow-2xl',
  },

  'clean-dark': {
    id: 'clean-dark',
    name: 'Modern Charcoal',
    category: 'dark',
    tagline: 'Balanced eye-safe neutral dark palette',
    dotColor: '#64748b',
    preview: {
      bg: 'bg-neutral-900',
      keyBg: 'bg-neutral-700',
      keyText: 'text-white',
      accent: 'bg-blue-600',
      border: 'border-neutral-600',
    },
    phoneShellBg: 'bg-neutral-950',
    phoneWallpaper: 'bg-neutral-950',
    statusBarClass: 'bg-neutral-900 text-neutral-200 border-b border-neutral-800',
    homeBarClass: 'bg-neutral-900',
    chatHeaderBg: 'bg-neutral-900 border-neutral-800 text-white',
    chatBodyBg: 'bg-neutral-950 text-white',
    chatQuickBarBg: 'bg-neutral-900/60 border-neutral-800/80',
    quickPromptChip: 'bg-neutral-800 hover:bg-neutral-750 text-neutral-200 border border-neutral-700/60 shadow-xs',
    userBubble: 'bg-blue-600 text-white shadow-xs',
    partnerBubble: 'bg-neutral-800 text-neutral-100 border border-neutral-700/60 shadow-xs',
    inputBarBg: 'bg-neutral-900 border-neutral-800',
    inputFieldBg: 'bg-neutral-800/70 border-neutral-700 text-white placeholder:text-neutral-500',
    smartBarBg: 'bg-neutral-850 border-neutral-700/60 text-white',
    smartBarBorder: 'border-neutral-700/60',
    pillBg: 'bg-neutral-800 border-neutral-700 text-neutral-200',
    accentColor: '#2563eb',
    keyboardChassisBg: 'bg-neutral-900 border-t border-neutral-800',
    keyNormal: 'bg-neutral-700 hover:bg-neutral-650 active:bg-neutral-600 text-white font-semibold shadow-[0_2px_0_0_#171717] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-neutral-800 hover:bg-neutral-750 active:bg-neutral-700 text-neutral-300 font-medium shadow-[0_2px_0_0_#141414] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-blue-600 text-white font-semibold shadow-[0_2px_0_0_#1e40af]',
    keySpace: 'bg-neutral-700 hover:bg-neutral-650 text-neutral-300 shadow-[0_2px_0_0_#171717] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-neutral-700 text-white border border-neutral-500 shadow-xl',
  },

  'clean-light': {
    id: 'clean-light',
    name: 'Modern Studio Light',
    category: 'light',
    tagline: 'High-clarity neutral light with crisp contrast',
    dotColor: '#94a3b8',
    preview: {
      bg: 'bg-neutral-100',
      keyBg: 'bg-white',
      keyText: 'text-neutral-900',
      accent: 'bg-blue-600',
      border: 'border-neutral-300',
    },
    phoneShellBg: 'bg-neutral-100',
    phoneWallpaper: 'bg-neutral-50',
    statusBarClass: 'bg-white text-neutral-800 border-b border-neutral-200',
    homeBarClass: 'bg-neutral-200',
    chatHeaderBg: 'bg-white border-neutral-200 text-neutral-900',
    chatBodyBg: 'bg-neutral-50 text-neutral-900',
    chatQuickBarBg: 'bg-neutral-50 border-neutral-200',
    quickPromptChip: 'bg-white hover:bg-neutral-100 text-neutral-800 border border-neutral-300 shadow-xs',
    userBubble: 'bg-blue-600 text-white shadow-xs',
    partnerBubble: 'bg-white text-neutral-900 border border-neutral-200 shadow-xs',
    inputBarBg: 'bg-white border-neutral-200',
    inputFieldBg: 'bg-neutral-100 border-neutral-300 text-neutral-900 placeholder:text-neutral-400',
    smartBarBg: 'bg-neutral-100 border-neutral-300 text-neutral-900',
    smartBarBorder: 'border-neutral-300',
    pillBg: 'bg-white border-neutral-300 text-neutral-800',
    accentColor: '#2563eb',
    keyboardChassisBg: 'bg-[#e5e7eb] border-t border-neutral-300',
    keyNormal: 'bg-white hover:bg-neutral-50 active:bg-neutral-200 text-neutral-900 font-semibold shadow-[0_2px_0_0_#cbd5e1] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-neutral-250 hover:bg-neutral-300 active:bg-neutral-350 text-neutral-800 font-medium shadow-[0_2px_0_0_#94a3b8] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-blue-600 text-white font-semibold shadow-[0_2px_0_0_#1e40af]',
    keySpace: 'bg-white hover:bg-neutral-50 text-neutral-500 shadow-[0_2px_0_0_#cbd5e1] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-white text-neutral-900 border border-neutral-300 shadow-xl',
  },

  'soft-sand': {
    id: 'soft-sand',
    name: 'Desert Dune',
    category: 'light',
    tagline: 'Warm earth tones that reduce eye strain',
    dotColor: '#b45309',
    preview: {
      bg: 'bg-[#ede5d8]',
      keyBg: 'bg-[#fffdfa]',
      keyText: 'text-stone-900',
      accent: 'bg-amber-600',
      border: 'border-stone-300',
    },
    phoneShellBg: 'bg-[#fcfaf6]',
    phoneWallpaper: 'bg-[#fcfaf6]',
    statusBarClass: 'bg-[#f5efe5] text-stone-800 border-b border-stone-300',
    homeBarClass: 'bg-[#ede5d8]',
    chatHeaderBg: 'bg-[#f7f2ea] border-stone-300 text-stone-900',
    chatBodyBg: 'bg-[#fcfaf6] text-stone-900',
    chatQuickBarBg: 'bg-[#ede5d8] border-stone-300',
    quickPromptChip: 'bg-[#fffdfa] hover:bg-[#f8f4ee] text-stone-800 border border-stone-300 shadow-xs',
    userBubble: 'bg-amber-700 text-white shadow-xs',
    partnerBubble: 'bg-[#fffdfa] text-stone-900 border border-stone-300 shadow-xs',
    inputBarBg: 'bg-[#f7f2ea] border-stone-300',
    inputFieldBg: 'bg-[#ede5d8] border-stone-300 text-stone-900 placeholder:text-stone-500',
    smartBarBg: 'bg-[#ede5d8] border-stone-300 text-stone-900',
    smartBarBorder: 'border-stone-300',
    pillBg: 'bg-[#fffdfa] border-stone-300 text-stone-800',
    accentColor: '#d97706',
    keyboardChassisBg: 'bg-[#ede5d8] border-t border-stone-300',
    keyNormal: 'bg-[#fffdfa] hover:bg-[#f8f4ee] active:bg-[#eee8df] text-stone-900 font-semibold shadow-[0_2px_0_0_#d6cbbe] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-[#e2dacb] hover:bg-[#d5ccbc] active:bg-[#c8bfae] text-stone-800 font-medium shadow-[0_2px_0_0_#b5a999] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-amber-600 text-white font-semibold shadow-[0_2px_0_0_#92400e]',
    keySpace: 'bg-[#fffdfa] hover:bg-[#f8f4ee] text-stone-500 shadow-[0_2px_0_0_#d6cbbe] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-[#fffdfa] text-stone-900 border border-stone-300 shadow-xl',
  },

  'high-contrast': {
    id: 'high-contrast',
    name: 'High Contrast Bold',
    category: 'dark',
    tagline: 'Maximum visibility & bold borders for clear reading',
    dotColor: '#eab308',
    badge: 'ACCESSIBLE',
    preview: {
      bg: 'bg-black',
      keyBg: 'bg-white',
      keyText: 'text-black',
      accent: 'bg-yellow-400',
      border: 'border-white',
    },
    phoneShellBg: 'bg-black',
    phoneWallpaper: 'bg-black',
    statusBarClass: 'bg-black text-white border-b border-neutral-800',
    homeBarClass: 'bg-black',
    chatHeaderBg: 'bg-black border-neutral-800 text-white',
    chatBodyBg: 'bg-black text-white',
    chatQuickBarBg: 'bg-black border-neutral-800',
    quickPromptChip: 'bg-neutral-900 hover:bg-neutral-800 text-white border border-neutral-700 shadow-xs',
    userBubble: 'bg-blue-600 text-white font-semibold border border-blue-400',
    partnerBubble: 'bg-neutral-900 text-white border border-neutral-700',
    inputBarBg: 'bg-black border-neutral-800',
    inputFieldBg: 'bg-neutral-900 border-neutral-700 text-white placeholder:text-neutral-400',
    smartBarBg: 'bg-black border-neutral-800 text-white',
    smartBarBorder: 'border-neutral-800',
    pillBg: 'bg-neutral-900 border-neutral-700 text-white',
    accentColor: '#eab308',
    keyboardChassisBg: 'bg-black border-t-2 border-neutral-700',
    keyNormal: 'bg-white hover:bg-neutral-100 active:bg-neutral-200 text-black font-bold border-2 border-neutral-400 shadow-[0_2px_0_0_#000] active:translate-y-[1px] active:shadow-none',
    keyAction: 'bg-neutral-800 hover:bg-neutral-700 active:bg-neutral-900 text-white font-bold border-2 border-neutral-600 shadow-[0_2px_0_0_#000] active:translate-y-[1px] active:shadow-none',
    keyActionActive: 'bg-yellow-500 text-black font-bold border-2 border-yellow-300 shadow-[0_2px_0_0_#000]',
    keySpace: 'bg-white hover:bg-neutral-100 text-black border-2 border-neutral-400 shadow-[0_2px_0_0_#000] active:translate-y-[1px] active:shadow-none',
    keyPopup: 'bg-black text-white border-2 border-white shadow-2xl',
  },
};

export function getThemeConfig(theme: KeyboardTheme): ThemeConfig {
  return THEME_CONFIGS[theme] || THEME_CONFIGS['cyber-slate'];
}

export const THEME_LIST: ThemeConfig[] = [
  THEME_CONFIGS['cyber-slate'],
  THEME_CONFIGS['nordic-frost'],
  THEME_CONFIGS['champagne-gold'],
  THEME_CONFIGS['emerald-sage'],
  THEME_CONFIGS['midnight-blue'],
  THEME_CONFIGS['ios-dark'],
  THEME_CONFIGS['ios-light'],
  THEME_CONFIGS['clean-dark'],
  THEME_CONFIGS['clean-light'],
  THEME_CONFIGS['soft-sand'],
  THEME_CONFIGS['high-contrast'],
];

